version: "3.9"

services:
  app:
    image: public.ecr.aws/z4s7o7l8/resume-api:v12
    environment:
      RAILS_ENV: production
      RAILS_LOG_TO_STDOUT: true
      RESUME_API_POSTGRES_USERNAME: app
      RESUME_API_POSTGRES_PASSWORD: letmein123
      RESUME_API_POSTGRES_HOST: db
      SECRET_KEY_BASE: test
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: postgres:15-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: letmein123
    ports:
      - "5432:5432"

volumes:
  postgres-data:
